### ISSUE TITLE
DESIGN: How should we manage shelter status and refugee status ?

### ISSUE THREAD

**Issue by Spectralgo** [hassanhabib/Refugee.Core#54]

**Comment by rcruzfreelance** [comment]
@Spectralgo may I recommend adding the modeling diagram/ER diagram to this project so we can have some standing to where. we should go for the Purpose of this  project. We could even include @hassanhabib to fully grasp the idea. I know there was a initial design in previous session, but having it in hand could help us further in future design ideas

**Comment by Spectralgo** [comment]
https://docs.refugee.land/docs/refugeeland.core/architecture
