### ISSUE TITLE
Data config: Creating DB configuration folder and on model creation with reflection

### ISSUE THREAD

**Issue by bramburn** [hassanhabib/Refugee.Core#66]

**Comment by Spectralgo** [comment]
Hi @bramburn, 

Thank you for the suggestion. I'm really glad you're taking up the time to share your thoughts. Let me take a minute to share ours.

Here are some explanation of The Standard DB configuration choices.

All configurations related to model projections to data models or anything related to the setting up of database communications is living in the StorageBroker class. The goal is to have those configurations, be as close as possible to the actual code managing calls to the database.

- StorageBroker is a partial class and lives across several files. 
- All files are focusing on one entity at a time.
- If we need configurations to manage relationships, we use a reference file, still part of the StorageBroker partial class.

You can take a look through the Otriples project to see examples of this implementation.

![image](https://user-images.githubusercontent.com/56794425/168283654-e61e8841-6514-4349-abfc-fef31545b47f.png)

Feel free to ask anything else or propose, nothing is in stone. 

**We might change something if you have good arguments for it.**  🙏
