### ISSUE TITLE
opensource group

### ISSUE THREAD

**Issue by bramburn** [hassanhabib/Refugee.Core#69]
Rather than holding the project under Hassan's profile would it be not be better having a separate public organization to build the application?

**Comment by Spectralgo** [comment]
I thought about it, and we might do it at some point, but I really wanted to grab the attention of people interested in Hassan's Standard. This is a great opportunity for this app to be able to rely on this community. I personally asked Hassan to create the project on his own account for this purpose. A lot of people are going through his GitHub repos to learn more about the Standard. Thanks again @hassanhabib for the support :-)
