### ISSUE TITLE
DATA: Contacts entity

### ISSUE THREAD

**Issue by bramburn** [hassanhabib/Refugee.Core#78]
to allow for the refugee or any other user entity to have specific contacts I propose the following data structure

- email:string
- phone?: string (using ISO e.10)

all fields are optional for contacting the user except email which I think should still be required for all users at this point in time.
so on Refugee entity the link would be 1-1

**Comment by bramburn** [comment]
@Spectralgo  can we go ahead with this?

**Comment by Spectralgo** [comment]
You can. But don't try to implement nullable with this Elvis notation or required with a notation attribute.

Make it simple and dumb, no logic should be in the model.

**Comment by bramburn** [comment]
What about creating a configuration file?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
