### ISSUE TITLE
DESIGN: Should we use PostgreSQL instead of MS SQL Server

### ISSUE THREAD

**Issue by Spectralgo** [hassanhabib/Refugee.Core#86]
![image](https://user-images.githubusercontent.com/56794425/172331683-9877a671-aa8a-449b-846e-18f4a65b5328.png)

I would like to use arrays or list of value types in our models.

@hassanhabib and @ElbekDeveloper What should I do ?
1. Create a string conversion in  OnModelCreating to handle this ?
    - pros: we can keep SQL Server
    - cons: it adds complexity
2.  Change EF config to use PostgreSQL instead of SQL Server
3. Use a secondary class to hold a value and make a list of those entities in my primary entity?

**Comment by bramburn** [comment]
keep it MSSQL 
what does the array of string hold? just create a separate data class to hold that one type.
